// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyApp.Web.Data;

#nullable disable

namespace StudyApp.Web.Migrations
{
    [DbContext(typeof(StudyDbContext))]
    [Migration("20260729134538_AddTopicPrerequisites")]
    partial class AddTopicPrerequisites
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("StudyApp.Core.Entities.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Back")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Due")
                        .HasColumnType("TEXT");

                    b.Property<double>("EaseFactor")
                        .HasColumnType("REAL");

                    b.Property<string>("Front")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("IntervalDays")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lapses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Repetitions")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceMaterialId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceReference")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceMaterialId");

                    b.HasIndex("UnitId");

                    b.HasIndex("DeckId", "Due");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.CardSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AcceptedCardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Back")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CourseTopicId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Front")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rationale")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceMaterialId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceReference")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("CourseTopicId");

                    b.HasIndex("SourceMaterialId");

                    b.HasIndex("UnitId");

                    b.HasIndex("CourseId", "Status");

                    b.ToTable("CardSuggestions");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.CardTopic", b =>
                {
                    b.Property<Guid>("CardId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseTopicId")
                        .HasColumnType("TEXT");

                    b.HasKey("CardId", "CourseTopicId");

                    b.HasIndex("CourseTopicId");

                    b.ToTable("CardTopics");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentUnitId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NotesMarkdown")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentUnitId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.CourseMapRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Status");

                    b.ToTable("CourseMapRevisions");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.CourseTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Importance")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ImportancePinned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImportanceReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDismissed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PreviousImportance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.HasIndex("CourseId", "Importance");

                    b.ToTable("CourseTopics");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.CourseUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("CourseId", "ParentId", "Order");

                    b.ToTable("CourseUnits");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.Deck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UnitId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.GenerationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MaterialId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("TargetTopicIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("CourseId", "Status");

                    b.ToTable("GenerationJobs");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DueDate");

                    b.HasIndex("UnitId");

                    b.HasIndex("CourseId", "Kind");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.MaterialExtract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PageCount")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Topics")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId")
                        .IsUnique();

                    b.ToTable("MaterialExtracts");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.ProgressSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("CapturedOn")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Learning")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Mastery")
                        .HasColumnType("REAL");

                    b.Property<int>("Mature")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RecallNow")
                        .HasColumnType("REAL");

                    b.Property<double?>("Retention")
                        .HasColumnType("REAL");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Unseen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Young")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "CapturedOn");

                    b.HasIndex("DeckId", "CapturedOn")
                        .IsUnique();

                    b.ToTable("ProgressSnapshots");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.ReviewLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CardId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Grade")
                        .HasColumnType("INTEGER");

                    b.Property<double>("IntervalAfterDays")
                        .HasColumnType("REAL");

                    b.Property<double>("IntervalBeforeDays")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("ReviewedAt");

                    b.ToTable("ReviewLogs");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.TopicPrerequisite", b =>
                {
                    b.Property<Guid>("CourseTopicId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrerequisiteTopicId")
                        .HasColumnType("TEXT");

                    b.HasKey("CourseTopicId", "PrerequisiteTopicId");

                    b.HasIndex("PrerequisiteTopicId");

                    b.ToTable("TopicPrerequisites");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.TopicProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CourseTopicId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MergeIntoTopicId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProposedImportance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProposedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProposedSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProposedUnitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseTopicId");

                    b.HasIndex("RevisionId");

                    b.ToTable("TopicProposals");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.TopicSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseTopicId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mention")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceReference")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseTopicId");

                    b.HasIndex("MaterialId", "Mention");

                    b.ToTable("TopicSources");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.Card", b =>
                {
                    b.HasOne("StudyApp.Core.Entities.Deck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyApp.Core.Entities.Material", "SourceMaterial")
                        .WithMany()
                        .HasForeignKey("SourceMaterialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudyApp.Core.Entities.CourseUnit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Deck");

                    b.Navigation("SourceMaterial");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.CardSuggestion", b =>
                {
                    b.HasOne("StudyApp.Core.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyApp.Core.Entities.CourseTopic", "Topic")
                        .WithMany()
                        .HasForeignKey("CourseTopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudyApp.Core.Entities.Material", "SourceMaterial")
                        .WithMany()
                        .HasForeignKey("SourceMaterialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudyApp.Core.Entities.CourseUnit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Course");

                    b.Navigation("SourceMaterial");

                    b.Navigation("Topic");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.CardTopic", b =>
                {
                    b.HasOne("StudyApp.Core.Entities.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyApp.Core.Entities.CourseTopic", "Topic")
                        .WithMany()
                        .HasForeignKey("CourseTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.Course", b =>
                {
                    b.HasOne("StudyApp.Core.Entities.CourseUnit", "CurrentUnit")
                        .WithMany()
                        .HasForeignKey("CurrentUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsMany("StudyApp.Core.Entities.AssessmentWeight", "AssessmentWeights", b1 =>
                        {
                            b1.Property<Guid>("CourseId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<int>("Kind");

                            b1.Property<int>("Weight");

                            b1.HasKey("CourseId", "__synthesizedOrdinal");

                            b1.ToTable("Courses");

                            b1
                                .ToJson("AssessmentWeights")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.Navigation("AssessmentWeights");

                    b.Navigation("CurrentUnit");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.CourseMapRevision", b =>
                {
                    b.HasOne("StudyApp.Core.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.CourseTopic", b =>
                {
                    b.HasOne("StudyApp.Core.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyApp.Core.Entities.CourseUnit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Course");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.CourseUnit", b =>
                {
                    b.HasOne("StudyApp.Core.Entities.Course", "Course")
                        .WithMany("Units")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyApp.Core.Entities.CourseUnit", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Course");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.Deck", b =>
                {
                    b.HasOne("StudyApp.Core.Entities.Course", "Course")
                        .WithMany("Decks")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyApp.Core.Entities.CourseUnit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Course");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.GenerationJob", b =>
                {
                    b.HasOne("StudyApp.Core.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyApp.Core.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Course");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.Material", b =>
                {
                    b.HasOne("StudyApp.Core.Entities.Course", "Course")
                        .WithMany("Materials")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyApp.Core.Entities.CourseUnit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Course");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.MaterialExtract", b =>
                {
                    b.HasOne("StudyApp.Core.Entities.Material", "Material")
                        .WithOne("Extract")
                        .HasForeignKey("StudyApp.Core.Entities.MaterialExtract", "MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("StudyApp.Core.Entities.ExtractSection", "Sections", b1 =>
                        {
                            b1.Property<Guid>("MaterialExtractId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Markdown")
                                .IsRequired();

                            b1.Property<int>("Page");

                            b1.Property<string>("Title")
                                .IsRequired();

                            b1.HasKey("MaterialExtractId", "__synthesizedOrdinal");

                            b1.ToTable("MaterialExtracts");

                            b1
                                .ToJson("Sections")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("MaterialExtractId");
                        });

                    b.OwnsMany("StudyApp.Core.Entities.ExtractTerm", "Terms", b1 =>
                        {
                            b1.Property<Guid>("MaterialExtractId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Definition")
                                .IsRequired();

                            b1.Property<string>("Term")
                                .IsRequired();

                            b1.HasKey("MaterialExtractId", "__synthesizedOrdinal");

                            b1.ToTable("MaterialExtracts");

                            b1
                                .ToJson("Terms")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("MaterialExtractId");
                        });

                    b.Navigation("Material");

                    b.Navigation("Sections");

                    b.Navigation("Terms");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.ProgressSnapshot", b =>
                {
                    b.HasOne("StudyApp.Core.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyApp.Core.Entities.Deck", "Deck")
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.ReviewLog", b =>
                {
                    b.HasOne("StudyApp.Core.Entities.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.TopicPrerequisite", b =>
                {
                    b.HasOne("StudyApp.Core.Entities.CourseTopic", "Topic")
                        .WithMany("Prerequisites")
                        .HasForeignKey("CourseTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyApp.Core.Entities.CourseTopic", "Prerequisite")
                        .WithMany()
                        .HasForeignKey("PrerequisiteTopicId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Prerequisite");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.TopicProposal", b =>
                {
                    b.HasOne("StudyApp.Core.Entities.CourseTopic", "Topic")
                        .WithMany()
                        .HasForeignKey("CourseTopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudyApp.Core.Entities.CourseMapRevision", "Revision")
                        .WithMany("Proposals")
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("StudyApp.Core.Entities.ProposedPrerequisite", "Prerequisites", b1 =>
                        {
                            b1.Property<Guid>("TopicProposalId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Name");

                            b1.Property<Guid?>("TopicId");

                            b1.HasKey("TopicProposalId", "__synthesizedOrdinal");

                            b1.ToTable("TopicProposals");

                            b1
                                .ToJson("Prerequisites")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("TopicProposalId");
                        });

                    b.OwnsMany("StudyApp.Core.Entities.ProposedSource", "Sources", b1 =>
                        {
                            b1.Property<Guid>("TopicProposalId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<Guid>("MaterialId");

                            b1.Property<int>("Mention");

                            b1.Property<string>("SourceReference");

                            b1.HasKey("TopicProposalId", "__synthesizedOrdinal");

                            b1.ToTable("TopicProposals");

                            b1
                                .ToJson("Sources")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("TopicProposalId");
                        });

                    b.Navigation("Prerequisites");

                    b.Navigation("Revision");

                    b.Navigation("Sources");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.TopicSource", b =>
                {
                    b.HasOne("StudyApp.Core.Entities.CourseTopic", "Topic")
                        .WithMany("Sources")
                        .HasForeignKey("CourseTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyApp.Core.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.Course", b =>
                {
                    b.Navigation("Decks");

                    b.Navigation("Materials");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.CourseMapRevision", b =>
                {
                    b.Navigation("Proposals");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.CourseTopic", b =>
                {
                    b.Navigation("Prerequisites");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.CourseUnit", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.Deck", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("StudyApp.Core.Entities.Material", b =>
                {
                    b.Navigation("Extract");
                });
#pragma warning restore 612, 618
        }
    }
}
